myproject/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
app_name = 'myapp'
urlpatterns = [
    path('', Test.as_view(), name='Test'),
    path('DashboardView/', DashboardView.as_view(), name='DashboardView'),
    path('DashboardColorView/', DashboardColorView.as_view(), name='DashboardColorView'),


    path('BuyerView/', BuyerView.as_view(), name='BuyerView'),
    path('StyleView/', StyleView.as_view(), name='StyleView'),
    path('ProductionLineView/', ProductionLineView.as_view(), name='ProductionLineView'),
    path('OrderQtyView/<int:id>/', OrderQtyView.as_view(), name='OrderQtyView'),
    path('SaveOrderQty/', SaveOrderQty.as_view(), name='SaveOrderQty'),
    path('OrederCMPreportView/', OrederCMPreportView.as_view(), name='OrederCMPreportView'),
    path('OrderQtyDetailView/<int:id>/',OrderQtyDetailView.as_view(), name='OrderQtyDetailView'),
    path('EditOrderQtyView/<int:pk>', EditOrderQtyView.as_view(), name='EditOrderQtyView'),
    path('ETAView/', ETAView.as_view(), name='ETAView'),

    path('ProductionInputView/', ProductionInputView.as_view(), name='ProductionInputView'),
    path('DailyProductionView/', DailyProductionView.as_view(), name='DailyProductionView'),
    path('DailyTargetView/', DailyTargetView.as_view(), name='DailyTargetView'),
    path('DailyTargetFilterView/', DailyTargetFilterView, name='DailyTargetFilterView'),
    path('LineDataEntryView/', LineDataEntryView, name='LineDataEntryView'),
    path('LineDataEntrySave/', LineDataEntrySave.as_view(), name='LineDataEntrySave'),
    path('ProductionLineOutputDetail/', ProductionLineOutputDetail.as_view(), name='ProductionLineOutputDetail'),

    path('DailyAttendanceView/', DailyAttendanceView.as_view(), name='DailyAttendanceView'),

    path('AccInventoyList/', AccInventoyList.as_view(), name='AccInventoyList'),
    path('AccVarientList/', AccVarientList.as_view(), name='AccVarientList'),
    path('create/', ProductCreate.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdate.as_view(), name='update_product'),
    path('delete-image/<int:pk>/', delete_image, name='delete_image'),
    path('delete-variant/<int:pk>/', delete_variant, name='delete_variant'),
    path('WarehouseMgrView/', WarehouseMgrView.as_view(), name='WarehouseMgrView'),
    path('AccRequestStatusChange/<int:pk>/', AccRequestStatusChange.as_view(), name='AccRequestStatusChange'),
    path('WH_to_Production_Acc/', WH_to_Production_Acc.as_view(), name='WH_to_Production_Acc'),

    path('FabricInvoiceList/', FabricInvoiceList.as_view(),name='FabricInvoiceList'),
    path('fabriccreate/', FabricProductCreate.as_view(), name='create_fabric'),
    path('fabricupdate/<int:pk>/', FabricProductUpdate.as_view(), name='update_fabric'),
    path('delete_fabric_image/<int:pk>/', delete_fabric_image, name='delete_fabric_image'),
    path('delete_fabric/<int:pk>/', delete_fabric, name='delete_fabric'),
    path('FabricRequesttoWH/', FabricRequesttoWH.as_view(), name='FabricRequesttoWH'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/templates/AccInventoyList.html
{% extends "base.html" %}


{% block content %}

<div class="row pb-10">

    <div class="col-xl-4 col-lg-4 col-md-6 mb-20">
        <div class="card-box height-100-p widget-style3">
            <div class="d-flex flex-wrap">
                <div class="widget-data">
                    <div class="weight-700 font-24 text-dark"><a href="{% url 'myapp:create_product' %}">Receive_Item</a></div>
                    <div class="font-14 text-secondary weight-500">

                    </div>
                </div>
                <div class="widget-icon">
                    <div class="icon" data-color="#05f511">
                        <i class="icon-copy dw dw-delivery-truck-2"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-6 mb-20">
        <div class="card-box height-100-p widget-style3">
            <div class="d-flex flex-wrap">
                <div class="widget-data">
                    <div class="weight-700 font-24 text-dark"><a href="{% url 'myapp:AccVarientList' %}">Output</a></div>
                    <div class="font-14 text-secondary weight-500">

                    </div>
                </div>
                <div class="widget-icon">
                    <div class="icon" data-color="#eb4034">

                        <i class="icon-copy dw dw-factory"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-6 mb-20">
        <div class="card-box height-100-p widget-style3">
            <div class="d-flex flex-wrap">
                <div class="widget-data">
                    <div class="weight-700 font-24 text-dark"><a href="{% url 'myapp:create_product' %}">Warehouse</a></div>
                    <div class="font-14 text-secondary weight-500">

                    </div>
                </div>
                <div class="widget-icon">
                    <div class="icon" data-color="#05f511">

                        <i class="icon-copy dw dw-profits-1"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Inventory Acc List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-success">

                <th class="">Buyer</th>
                <th class="">PO#</th>
                                <th class="">Receive Qty</th>
                                <th>Receive Date</th>
                <th class="">Edit</th>
                <th class="">Warehouse</th>




            </tr>
            </thead>
            <tbody>
            {% for a in acc %}
            <tr class="">
                <td class="table-plus"><a href="#"><b>{{a.buyer_name}}</b></a></td>
                <td class="">{{ a.po_style_no }}</td>
                                <td>{{a.receive_qty}}</td>
                <td class=""><a href="#"><b>{{a.sku}}</b></a></td>
                <td class=""><a href="{% url 'myapp:update_product' a.id %}" class="btn btn-sm btn-info"><i class="icon-copy dw dw-edit-file"></i></a></td>
                <td>{{a.warehouse}}</td>



            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

myproject/templates/DailyProductionView.html
{% extends 'base.html' %}

{% block content %}


<!-- ---------table--------- -->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Daily Production</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-primary">

                <th class="">Line Name</th>

                <th class="">InStock</th>
                <th class="">TargetQty</th>
                <th>total output</th>
                <th>
                    %
                </th>


            </tr>
            </thead>
            <tbody>
            {% for p in daily_target_view %}
            <tr class="">
                <td class="table-plus"><a href="{% url 'myapp:LineDataEntryView' %}?pline={{p.line}}"
                                          class="text-primary font-weight-bold d-block"><strong>{{p.line}}</strong></a>
                </td>

                <td>{{p.stock}}</td>
                <td>{{p.daily_target}}</td>
                <td>
                    {{p.t_total_output_qty}}


                </td>
                <td>

                    <script>document.write({{p.t_total_output_qty}}/{{p.sum}}*100);</script>
                    %


                </td>


            </tr>
            {% endfor %}

            </tbody>

        </table>

    </div>

</div>


{% endblock content %}

myproject/templates/DailyTargetView.html
{% extends 'base.html' %}

{% block content %}


<div class="row">

<div class="col-lg-3 col-md-6 col-sm-12 mb-1">
                            <div class="pd-20 card-box height-100-p">
                                <h4 class="mb-20 h4">Production Lines</h4>
                                <div class="list-group">
                                    <a href="{% url 'myapp:DailyTargetView' %}" class="list-group-item list-group-item-action active"><h5>All</h5></a>

                                    {% for i in line %}
                                    <a href="{% url 'myapp:DailyTargetFilterView' %}?pline={{i.ProductionLine}}" class="list-group-item list-group-item-action"><h5>{{i.ProductionLine}}</h5></a>

                                    {% endfor %}
                                    
                                </div>
                            </div>
                        </div>

<!-- ----------------------- -->
<div class="card-box height-100-p col-md-9">
    <br>
    <h3 class="mb-20 h4">Daily Target Production</h3>
<div class="pb-20">

        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-primary">

                <th class="">Line Name</th>
                <th class="">Style</th>
                <th class="">Daily Target Qty</th>
                                <th class="">Status</th>
                <!--                <th>Vou</th>-->


            </tr>
            </thead>
            <tbody>
            {% for p in pro_input %}
            <tr class="">
                <td class="table-plus">{{p.line}}</td>
                <td>
                
                <!-- ------------------------- -->
                <a
                    href="#"
                    class="btn-block text-blue"
                    data-toggle="modal"
                    data-target="#bd-example-modal-lg{{p.id}}"
                    type="button"
            >
               
                <strong>{{p.style}}</strong>
            </a>
            <div
                    class="modal fade bs-example-modal-lg"
                    id="bd-example-modal-lg{{p.id}}"
                    tabindex="-1"
                    role="dialog"
                    aria-labelledby="myLargeModalLabel"
                    aria-hidden="true"
            >
                <div class="modal-dialog modal-lg modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myLargeModalLabel">
                                {{p.line}}
                            </h4>
                           
                            <button
                                    type="button"
                                    class="close"
                                    data-dismiss="modal"
                                    aria-hidden="true"
                            >
                                ×
                            </button>
                        </div>
                        <form action="{% url 'myapp:DailyTargetView' %}" method="post">{% csrf_token %}
                        <div class="modal-body">
                            <h5>Style No - {{p.style}}</h5>
                            <input type="text" value="{{p.line}}" name="line" hidden>
                            <input type="text" value="{{p.style}}" name="style" hidden>
                            <input type="text" value="{{p.input_qty}}" name="input_qty" hidden>
                            <br>

                            
                            <div class="form-group row">
                                <label class="col-sm-12 col-md-2 col-form-label">Daily Target Qty</label>
                                <div class="col-sm-12 col-md-8">
                                    <input class="form-control" type="number" value ="{{p.daily_target}}" name="target_qty">
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button
                                    type="button"
                                    class="btn btn-outline-secondary"
                                    data-dismiss="modal"
                            >
                                Close
                            </button>
                            <button type="submit" class="btn btn-success">
                                Save Target
                            </button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
                <!-- ---------------------- -->
                </td>
                <td>{{p.daily_target}}</td>
                {% if p.status == False %}
                                <td><span class="badge badge-pill badge-warning">pending</span></td>
                {% else %}
                <td><span class="badge badge-pill badge-success">finish</span></td>
                {% endif %}


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>



</div>

</div>

</div>


<hr>

<div class="card-box mb-30">
    <div class="pd-20">
                <h4 class="text-blue h4"><i class="micon dw dw-karate"></i>-Garment Factory</h4>
        
    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-primary">

                <th class="">Line Name</th>
                <th class="">Style Code</th>
                <th class="">InputQty</th>
                <th class="">TargetQty</th>
                <th>New Order</th>


            </tr>
            </thead>
            <tbody>
            {% for p in daily_target_view %}
            <tr class="">
                <td class="table-plus"><a href="#"><b>{{p.line}}</b></a></td>
                <td>{{p.style}}</td>
                <td>{{p.input_qty}}</td>
                <td>{{p.daily_target}}</td>
                <td>
                    *
                </td>


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>



{% endblock content %}

myproject/templates/FabricInvoiceList.html
{% extends "base.html" %}


{% block content %}

<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Inventory Fabric Invoice List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-success">

                <th class="">Supplier</th>
                <th class="">Buyer</th>
                                <th class="">PO</th>
                                <th>Receive Qty</th>
                <th class="">Edit</th>
                <th class="">Warehouse</th>




            </tr>
            </thead>
            <tbody>
            {% for a in fab_inv %}
            <tr class="">
                <td class="table-plus"><a href="#"><b>{{a.supplier_name}}</b></a></td>
                <td class="">{{ a.buyer_name }}</td>
                                <td>{{a.po_style_no}}</td>
                <td class=""><a href="#"><b>{{a.receive_qty}}</b></a></td>
                <td class=""><a href="{% url 'myapp:update_fabric' a.id %}" class="btn btn-sm btn-info"><i class="icon-copy dw dw-edit-file"></i></a></td>
                <td>{{a.warehouse}}</td>



            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>


<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Fabric Composition List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-success">

                <th class="">PO#</th>
                <th class="">Fabric Composition</th>
                                <th class="">Color</th>
                                <th>Avaiable Qty</th>
                <th class="">Edit</th>
                <th class="">Warehouse</th>




            </tr>
            </thead>
            <tbody>
            {% for a in fab_compo %}
            <tr class="">
                <td class="table-plus"><a href="#"><b>{{a.accinv}}</b></a></td>
                <td class="">{{ a.fabric_composition }}</td>
                                <td>{{a.color}}</td>
                <td class=""><a href="#"><b>{{a.receive_qty}}</b></a></td>
                <td class="">{{a.fabric_width}}</td>
                <td></td>



            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>




{% endblock content %}

myproject/templates/ProductionLineView.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h5>New Production Line</h5>

            </div>
            <hr>

        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <form action="{% url 'myapp:ProductionLineView' %}" method="post">{% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Production Line</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="line">
                    </div>
                </div>


                {% if message %}
                <li class="text-danger">{{message}}</li>

                {% endif %}
                {% if success %}
                <div class="text-success" role="">
                    {{success}}
                </div>
                {% endif %}

                <input type="submit" value="Add Production Line" class="btn btn-primary">


            </form>
        </div>
    </div>
</div>


<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Production Line List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-success">

                <th class="text-center">#</th>
                <th class="text-center">ProductionLine</th>
                <!--                <th class="text-center">More</th>-->
                                <th>Daily Target</th>


            </tr>
            </thead>
            <tbody>
            {% for p in line %}
            <tr class="">
                <td class="table-plus text-center"><a href="#"><b>{{p.id}}</b></a></td>
                <td class="text-center">{{p.ProductionLine}}</td>
                                <td>{{p.daily_target}}</td>


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

myproject/templates/fabric_create_or_update.html
<!-- product_create_or_update.html -->

{% extends "base.html" %}

{% block content %}
<form enctype="multipart/form-data" class="container" method="post" id="product_form">
    {% csrf_token %}
    <!-- main form start --- in our case product form -->
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">Add Products</h4>
        </div>
        {% for field in form %}
            <div class="form-group card-body">
                <label>{{field.label}}</label>
                {% if field.field.required %}
                    <span style="color: red;" class="required">*</span>
                {% endif %}

                {{field}}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <!-- main form end --- in our case product form -->

    <!-- inline form for Images start -->

    <!-- EXPLAINING with named_formsets.images as formset -->
    <!-- Note: named_formsets is used in get_context_data function in views.py -->
    <!-- Note: here images is our ImageFormSet name, used in get_named_formsets function in views.py -->
    {% with named_formsets.images as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="images-template">   // id="inlineformsetname-template"
            <tr id="images-__prefix__" class= hide_all>  // id="inlineformsetname-__prefix__"
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}

                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>

        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Add Images</h4>
            </div>
            <table class="table card-body">
                <thead class="text-secondary">
                    <th>Image <span style="color: red;" class="required">*</span></th>
                    <th>Delete?</th>
                    <th>Custom Delete btn</th>
                </thead>
                <tbody id="item-images">  <!-- id="item-inlineformsetname" -->
                    <!-- formset non forms errors -->
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="images-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                </td>
                            {% endfor %}
                            <!-- delete code -->
                            {% if formss.instance.pk %}
                                <td>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalq{{formss.instance.pk}}">
                                        Delete
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModalq{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalq{{formss.instance.pk}}">Are Your Sure You Want To Delete This?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'myapp:delete_fabric_image' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-image-button" class="btn btn-secondary add-images">Add More</a> <!-- id="add-inlineformsetname-button" -->
        </div>
    {% endwith %}
    <!-- inline form for Images end -->

    <!-- inline form for Variant start -->

    <!-- EXPLAINING with named_formsets.variants as formset -->
    <!-- Note: named_formsets is used in get_context_data function in views.py -->
    <!-- Note: here variants is our VariantFormSet name, used in get_named_formsets function in views.py -->
    {% with named_formsets.variants as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="variants-template">  // id="inlineformsetname-template"
            // id='inlineformsetname-__prefix__'
            <tr id="variants-__prefix__" class= hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}

                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Add Variants</h4>
            </div>
            <table class="table card-header">
                <thead class="text-secondary">
                    <th>ပိတ်စ ဖွဲ့စည်းပံု <span style="color: red;" class="required">*</span></th>
                    <th>အ ေရာင် <span style="color: red;" class="required">*</span></th>
                    <th>အရှည် (ကိုက်) <span style="color: red;" class="required">*</span></th>
                    <th>Roll</th>
                    
                    <th>Delete?</th>
                    <th>Remove</th>
                </thead>
                <tbody id="item-variants">  <!-- id="item-inlineformsetname" -->
                    <!-- formset non forms errors -->
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="variants-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}

                                    {% comment %} {{ field.DELETE }} {% endcomment %}
                                </td>
                            {% endfor %}
                            {% comment %} for delete {% endcomment %}
                            {% if formss.instance.pk %}
                                <td>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{formss.instance.pk}}">
                                        Delete
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">Are Your Sure You Want To Delete This?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'myapp:delete_fabric' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-variant-button" class="btn btn-secondary add-variants">Add More</a> <!-- id="add-inlineformsetname-button" -->
        </div>

        {% endwith %}
        <!-- inline form for Images end -->

        <div class="form-group">
            <button type="submit" class="btn btn-secondary btn-block">Submit</button>
        </div>
</form>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    $(document).ready(function() {
        // when user clicks add more btn of images
      $('.add-images').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-images').children().length;
          var tmplMarkup = $('#images-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-images').append(compiledTmpl);

          // update form count
          $('#id_images-TOTAL_FORMS').attr('value', count+1);
      });
  });

  $(document).ready(function() {
    // when user clicks add more btn of variants
      $('.add-variants').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-variants').children().length;
          var tmplMarkup = $('#variants-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-variants').append(compiledTmpl);

          // update form count
          $('#id_variants-TOTAL_FORMS').attr('value', count+1);
      });
  });
</script>

{% endblock content %}